using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;

[assembly: InternalsVisibleTo("SimpleUIScreensSystem.Generator.Editor.Tests")]

namespace SimpleUIScreensSystem.Editor
{
    internal static class ScreenKeysGenerator
    {
        private const string GeneratedHeader = "// <auto-generated />\n";
        private static readonly HashSet<string> Keywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
            "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
            "using", "virtual", "void", "volatile", "while", "__arglist", "__makeref", "__reftype",
            "__refvalue", "add", "alias", "and", "ascending", "async", "await", "by", "descending",
            "dynamic", "equals", "file", "from", "get", "global", "group", "init", "into", "join",
            "let", "managed", "nameof", "nint", "not", "notnull", "nuint", "on", "or", "orderby",
            "partial", "record", "remove", "required", "scoped", "select", "set", "unmanaged",
            "value", "var", "when", "where", "with", "yield"
        };

        internal readonly struct Entry
        {
            public Entry(ScreenId id, string codeName)
            {
                Id = id;
                CodeName = codeName;
            }

            public ScreenId Id { get; }
            public string CodeName { get; }
        }

        public static string Generate(string namespaceName, string className, string catalogGuid,
            IReadOnlyList<Entry> entries)
        {
            ValidateNamespace(namespaceName);
            RequireIdentifier(className, "Class name");
            if (entries == null) throw new ArgumentNullException(nameof(entries));

            var sorted = ValidateEntries(entries, className);
            sorted.Sort((left, right) => StringComparer.Ordinal.Compare(left.CodeName, right.CodeName));

            var source = new StringBuilder(GetHeader(catalogGuid));
            source.Append("// Generated from the screen catalog. Regenerate after changing code names or entries.\n\n");
            source.Append("namespace ").Append(namespaceName).Append("\n{\n");
            source.Append("    public static class ").Append(className).Append("\n    {\n");
            foreach (var entry in sorted)
            {
                source.Append("        public static readonly global::SimpleUIScreensSystem.ScreenId ")
                    .Append(entry.CodeName)
                    .Append(" = new global::SimpleUIScreensSystem.ScreenId(\"")
                    .Append(EscapeString(entry.Id.Value)).Append("\");\n");
            }
            return source.Append("    }\n}\n").ToString();
        }

        public static bool IsOwnedByCatalog(string source, string catalogGuid)
        {
            return source != null && source.Replace("\r\n", "\n")
                .StartsWith(GetHeader(catalogGuid), StringComparison.Ordinal);
        }

        private static string GetHeader(string catalogGuid)
        {
            if (!Guid.TryParseExact(catalogGuid, "N", out var guid))
                throw new ArgumentException("The catalog must be a saved asset with a valid GUID.", nameof(catalogGuid));
            return GeneratedHeader + "// Simple UI screen keys. Catalog GUID: " + guid.ToString("N") + "\n";
        }

        private static List<Entry> ValidateEntries(IReadOnlyList<Entry> entries, string className)
        {
            var ids = new HashSet<ScreenId>();
            var names = new HashSet<string>(StringComparer.Ordinal);
            var result = new List<Entry>(entries.Count);
            foreach (var entry in entries)
            {
                if (!entry.Id.IsValid)
                    throw new InvalidOperationException("Every screen needs a nonempty stable ID.");
                if (!ids.Add(entry.Id))
                    throw new InvalidOperationException($"Duplicate screen ID '{entry.Id.Value}'. Assign a new ID to the copied entry before generating keys.");
                RequireIdentifier(entry.CodeName, $"Code name for screen '{entry.Id.Value}'");
                if (string.Equals(entry.CodeName, className, StringComparison.Ordinal))
                    throw new InvalidOperationException($"Screen code name '{entry.CodeName}' cannot equal its generated class name.");
                if (!names.Add(entry.CodeName))
                    throw new InvalidOperationException($"Duplicate screen code name '{entry.CodeName}'.");
                result.Add(entry);
            }
            return result;
        }

        private static void ValidateNamespace(string namespaceName)
        {
            if (string.IsNullOrEmpty(namespaceName))
                throw new ArgumentException("Choose a namespace for the generated keys, for example Game.UI.");
            foreach (var part in namespaceName.Split('.')) RequireIdentifier(part, "Namespace segment");
        }

        private static void RequireIdentifier(string value, string description)
        {
            if (string.IsNullOrEmpty(value) || Keywords.Contains(value) || !IsIdentifierStart(value[0]))
                throw new ArgumentException($"{description} '{value}' must be a C# identifier using letters A-Z, a-z, digits and underscores; keywords are not allowed.");
            for (var i = 1; i < value.Length; i++)
            {
                if (!IsIdentifierStart(value[i]) && (value[i] < '0' || value[i] > '9'))
                    throw new ArgumentException($"{description} '{value}' contains an unsupported identifier character.");
            }
        }

        private static bool IsIdentifierStart(char character)
        {
            return character == '_' || character >= 'A' && character <= 'Z' || character >= 'a' && character <= 'z';
        }

        private static string EscapeString(string value)
        {
            var result = new StringBuilder(value.Length);
            foreach (var character in value)
            {
                switch (character)
                {
                    case '\\': result.Append("\\\\"); break;
                    case '"': result.Append("\\\""); break;
                    case '\n': result.Append("\\n"); break;
                    case '\r': result.Append("\\r"); break;
                    case '\t': result.Append("\\t"); break;
                    default:
                        if (character < ' ' || character > '~')
                            result.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                        else
                            result.Append(character);
                        break;
                }
            }
            return result.ToString();
        }
    }
}
